apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-deploy
  labels:
    app: proj-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proj-deploy
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: proj-deploy
    spec:
      containers:
        - name: mysite
          image: shrewdrowny/djangoapp:v29
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret
