apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-deploy
  labels:
    app: proj-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj-deploy
  template:
    metadata:
      labels:
        app: proj-deploy
    spec:
      containers:
        - name: mysite
          image: shrewdrowny/djangoapp:v8
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret
